AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless bug
Resources:

  Bucket:
    Type: AWS::S3::Bucket
      
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Runtime: nodejs6.10
      Handler: index.handler
      Policies:
        - Version: 2012-10-17
          Statement: 
            - Effect: Allow
              Action: s3:*
              Resource: !Sub "arn:aws:s3:::${Bucket}*"
      Events:
        Upload:
          Properties:
            Bucket:
              Ref: Bucket
            Events: s3:ObjectCreated:*
          Type: S3
