AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless bug
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  Function:
    Properties:
      CodeUri: s3://storeapp-build-artifacts/fb5a16d08daaa60d9e9f507a3d7199fc
      Events:
        Upload:
          Properties:
            Bucket:
              Ref: Bucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: index.handler
      Policies:
      - Statement:
        - Action: s3:*
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${Bucket}*
        Version: 2012-10-17
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
